name: CI for POS

on:
  push:
    branches: [ main ]

jobs:
  render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # No GHCR push, Render will build automatically when you push to main
